APStore/APStore/Controllers/ShopController.cs
using APStore.Common;
using APStore.Models.DAO;
using APStore.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APStore.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index()
        {
            var listCategory = new ProductCategoryDAO().ListAll();
            ViewBag.ListCategory = listCategory;
            var model = new ProductDao().ListAll();
            return View(model);
        }
        [HttpGet]
        public ActionResult Detail(int id)
        {
            var listProduct = new ProductDao().ListAll();
            ViewBag.ListProduct = listProduct;
            var model = new ProductDao().Get(id);
            return View(model);
        }
        public ActionResult LogOut()
        {
            Session[Constant.UserLoginSession] = null;
            return RedirectToAction("Index", "Shop");
        }
        [ChildActionOnly]
        public ActionResult Top()
        {
            UserLogin current = (UserLogin)Session[Constant.UserLoginSession];
            if (current != null)
            {
                List<Cart> carts = new CartDAO().ListAll(current.Name);
                foreach (var item in carts)
                {
                    Product p = new ProductDao().Get(item.ProductID);
                    item.ProductNameDisplay = p.Name;
                    item.ProductImagePathDisplay = p.ImagePath;
                    item.ProductPriceDisplay = p.Price;
                    int CategoryID = p.CategoryID;
                    item.ProductCategoryDisplay = new ProductCategoryDAO().Get(CategoryID).Name;
                }
                ViewBag.Carts = carts;
                ViewBag.Count = carts.Count;
            }
            return PartialView(current);
        }
    }
}

APStore/APStore/Controllers/UserLoginController.cs
using APStore.Common;
using APStore.Models.DAO;
using APStore.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace APStore.Controllers
{
    public class UserLoginController : Controller
    {
        // GET: UserLogin
        public ActionResult Index()
        {
            var sess = (UserLogin)Session[Constant.UserLoginSession];
            if (sess != null)
            {
                return RedirectToAction("Index", "Shop");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UserLogin obj)
        {
            if (ModelState.IsValid)
            {
                LoginStatus result = new UserLoginDAO().Login(obj);
                switch (result)
                {
                    case LoginStatus.Success:
                        UserLogin sessionlogin = new UserLogin();
                        sessionlogin = new UserLoginDAO().GetLogin(obj.Name);
                        Session.Add(Constant.UserLoginSession, sessionlogin);
                        return RedirectToAction("Index", "Shop");
                    case LoginStatus.UserNameFail:
                        ModelState.AddModelError("", "Không tồn tại User : " + obj.Name);
                        break;
                    case LoginStatus.PasswordFail:
                    default:
                        ModelState.AddModelError("", "Mật khẩu không đúng!");
                        break;
                }
            }
            return View();
        }

        public ActionResult Register()
        {
            var sess = (UserLogin)Session[Constant.UserLoginSession];
            if (sess != null)
            {
                return RedirectToAction("Index", "Shop");
            }
            return View();
        }
        [HttpPost] 
        public ActionResult Register(UserLogin obj)
        {
            if (ModelState.IsValid)
            {
                bool result = new UserLoginDAO().Register(obj);
                if (result)
                {
                    UserLogin sessionlogin = new UserLogin();
                    sessionlogin = new UserLoginDAO().GetLogin(obj.Name);
                    Session.Add(Constant.UserLoginSession, sessionlogin);
                    return RedirectToAction("Index", "Shop");
                }
                else
                {
                    ModelState.AddModelError("", "Đã có user "+obj.Name);
                }
            }
            return View();
        }
    }
}

APStore/APStore/Views/Shop/Detail.cshtml
@model APStore.Models.Entities.Product
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="app">
    <div class="container">
        <div class="row product">
            <div class="col col-lg-5 col-md-5 col-sm-12">
                <div class="depicted-product">
                    <div class="row">
                        <div class="col col-12">
                            <img src="@Model.ImagePath" alt="product" class="depicted-product__img">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-12 depicted-product__img-list">
                            <img src="@Model.ImagePath" alt="product" class="depicted-product__img-item">
                            <img src="@Model.ImagePath" alt="product" class="depicted-product__img-item">
                            <img src="@Model.ImagePath" alt="product" class="depicted-product__img-item">
                            <img src="@Model.ImagePath" alt="product" class="depicted-product__img-item">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-12 depicted-product__social">
                            <div class="depicted-product__social-share">
                                <span>Chia sẻ:</span>
                                <a href="#">
                                    <i class="fab fa-facebook-messenger social-share--messenger"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-facebook social-share--facebook"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-google-plus social-share--google-plus"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-pinterest social-share--pinterest"></i>
                                </a>
                                <a href="#">
                                    <i class="fab fa-twitter-square social-share--twitter"></i>
                                </a>
                            </div>
                            <div class="depicted-product__social-like">
                                <i class="far fa-heart social-like--heart"></i>
                                <span class="depicted-product__social-like__number">Đã thích (6,7k)</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col col-lg-7 col-md-7 col-sm-12">
                <div class="sale-product">
                    <div class="product__name">@Model.Name</div>
                    <div class="product-reviews">
                        <div class="product-reviews__star">
                            <span class="product-reviews__star-number">4.9</span>
                            <div>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                            </div>
                        </div>
                        <div class="product-reviews__detail">
                            <span class="product-reviews__detail-number">3,4K</span>
                            <span class="product-reviews__detail-title">Đánh giá</span>
                        </div>
                        <div class="product-reviews__sold">
                            <span class="product-reviews__sold-number">3,6K</span>
                            <span class="product-reviews__sold-title">Đã bán</span>
                        </div>
                    </div>
                    <div class="product-price">
                        <div class="product-price__detail">
                            <div class="product-price__detail-old"><span>₫</span>153.000</div>
                            <div class="product-price__detail-new"><span>₫</span>@Model.Price.ToString("#,##")</div>
                            <div class="product-price__detail-percent">39% GIẢM</div>
                        </div>
                        <div class="product-price__title">
                            @*<img src="~/Assets/f8-shop/assets/img/saleOff.png" alt="sale off" class="product-price__title-img">*@
                            @*<div class="product-price__title-desc">Ở đâu rẻ hơn, Shopee hoàn tiền</div>*@
                        </div>
                    </div>
                    <div class="row product-option">
                        <div class="col col-12">
                            @*<div class="product-option__select">
                                    <div class="product-option__select-title">Deal sốc</div>
                                    <div class="product-option__select-desc">Mua kèm Deal sốc</div>
                                </div>*@
                            <div class="product-option__select">
                                <div class="product-option__select-title">Vận chuyển</div>
                                <div class="product-option__select-desc">
                                    <div class="product-option__select-free-ship">
                                        <div class="product-option__select-free-ship-title">
                                            <img src="~/Assets/f8-shop/assets/img/FreeShip.png" alt="free ship"
                                                 class="product-option__select-free-ship-img">
                                            <div class="product-option__select-free-ship-text">
                                                Miễn Phí Vận Chuyển
                                            </div>
                                        </div>
                                        <div class="product-option__select-free-ship-decs">
                                            Miễn Phí Vận Chuyển khi đơn đạt giá trị tối thiểu
                                        </div>
                                    </div>
                                    <div class="product-option__select-ship-to">
                                        <div class="product-option__select-ship-to-title">
                                            <i class="fas fa-box product-option__select-ship-to-icon"></i>
                                            <div class="product-option__select-ship-to-text">
                                                Vận chuyển tới <span> Huyện Ba Vì, Hà Nội</span>
                                            </div>
                                        </div>
                                        <div class="product-option__select-ship-to-decs">
                                            Phí vận chuyển ₫43.737 - ₫55.370
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="product-option__select">
                                <div class="product-option__select-title product-option__select-color-title">
                                    Màu sắc
                                </div>
                                <div class="product-option__select-desc">
                                    <button type="button"
                                            class="btn product-option__select-btn-color">
                                        Trắng
                                    </button>
                                    <button type="button" class="btn product-option__select-btn-color">Đen</button>
                                    <button type="button" class="btn product-option__select-btn-color">Xanh</button>
                                    <button type="button" class="btn product-option__select-btn-color">Hồng</button>
                                </div>
                            </div>
                            <div class="product-option__select">
                                <div class="product-option__select-title product-option__select-quantity-product-title">
                                    Số lượng
                                </div>
                                <div class="product-option__select-desc product-option__select-quantity-product">
                                    <div class="quantity-product">
                                        <button class="btn-sub-quantity">-</button>
                                        <input id="quantities" type="number" min="1" class="input-quantity" value="1">
                                        <button class="btn-add-quantity">+</button>
                                    </div>
                                    <div>462 sản phẩm có sẵn</div>
                                </div>
                            </div>
                            <div class="product-option__select">
                                <button type="button" onclick="AddProduct(@Model.ID)" class="product-option-btn btn-add-to-cart">
                                    Thêm vào giỏ hàng
                                </button>
                                <button type="button" class="product-option-btn btn-buy-now">Mua ngay</button>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="guarantee-product" href="#">
                    <div>
                        <img src="~/Assets/f8-shop/assets/img/GuaranteeProduct.png" alt="guarantee product"
                             class="guarantee-product-img">
                        <span class="guarantee-product-title">Shopee Đảm Bảo</span>
                    </div>
                    <span class="guarantee-product-desc">3 Ngày Trả Hàng / Hoàn Tiền</span>
                </a>
            </div>
        </div>
    </div>
</div>

<script>
    function AddProduct(id, userName) {
        var quantities = document.getElementById("quantities").value;
        console.log(quantities);
        var data = new FormData();
        data.append("ID", id);
        data.append("Quantities", quantities);
        $.ajax({
            type: "POST",
            url: '/Cart/AddProduct',
            data: data,
            contentType: false,
            processData: false,
            success: function (response) {
                if (response == "NotLogin") {
                    window.location.href = '@Url.Action("Index", "UserLogin")';
                    console.log(response);
                }
                else if (response) {
                    console.log(response)
                    var cart = JSON.parse(response);
                    var content = ('<li class="header__cart-item" id="li_'+cart.ProductID+'">');
                    content += '<img src="'+cart.ProductImagePathDisplay+'" alt="" class="header__cart-img">';
                    content += '<div class="header__cart-item-info">';
                    content += '<div class="header__cart-item-head">';
                    content += '<h5 class="header__cart-item-name">';
                    content += cart.ProductNameDisplay;
                    content += '</h5>';
                    content += '<div class="header__cart-item-price-wrap">';
                    content += '<span class="header__cart-item-price">' + cart.ProductPriceDisplay +'</span>';
                    content += '<span class="header__cart-item-multiply">x</span>';
                    content += '<span class="header__cart-item-qnt" id="product_quantities_'+cart.ProductID+'">' + quantities + '</span>';
                    content += '</div>';
                    content += '</div>';
                    content += '<div class="header__cart-item-body">';
                    content += '<span class="header__cart-item-description">';
                    content += 'Phân loại'+ cart.ProductCategoryDisplay;
                    content += '</span>';
                    content += '<span class="header__cart-item-remove"><a  onclick="DeleteProduct('+id+')">Bỏ</a></span>';
                    content += '</div>';
                    content += '</div>';
                    content += '</li>';
                    var list_item = document.getElementById("li_" + id);
                    if (list_item) {
                        var tagQuantites = document.getElementById("product_quantities_" + id);
                        var currentQuanties = Number.parseInt(tagQuantites.innerHTML);
                        currentQuanties += Number.parseInt(quantities);
                        tagQuantites.innerHTML = currentQuanties;
                    }
                    else {
                        var tagCount = document.getElementById("cart_count");
                        var count = Number.parseInt(tagCount.innerHTML);
                        count += 1;
                        tagCount.innerHTML = count;
                        $('#list_cart').append(content);
                    }
                    alert("Thêm thành công sản phẩm vào giỏ hàng")
                }
                else {
                    alert("Không thể thêm sản phẩm vào giỏ hàng")
                }
            }
        });
    }


</script>

APStore/APStore/Views/Shop/Index.cshtml
@model List<APStore.Models.Entities.Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="app__container">
    <div class="grid wide">
        <div class="row-lbr sm-gutter app__content">
            <div class="col-lbr l-2 m-0 c-0-lbr">
                <nav class="category">
                    <h3 class="category__heading">
                        <i class="category__heading-icon fas fa-list-ul"></i>
                        Danh mục
                    </h3>
                    <ul class="category-list">
                        <li class="category-item category-item--active">
                            <a href="#" class="category-item__link">Hạt</a>
                        </li>
                        @foreach (var item in ViewBag.ListCategory)
                        {
                            <li class="category-item ">
                                <a href="#" class="category-item__link">@item.Name</a>
                            </li>
                        }
                    </ul>
                </nav>
            </div>

            <div class="col-lbr l-10 m-12 c-12">
                <div class="home-filter hide-on-mobile-tablet">
                    <span class="home-filter__label">Sắp xếp theo</span>
                    <button class="home-filter__btn btn">Loại</button>
                    <button class="home-filter__btn btn btn--primary">Mới nhất</button>
                    <button class="home-filter__btn btn">Bán chạy</button>

                    <div class="select-input">
                        <span class="select-input__label">Giá</span>
                        <i class="fas fa-angle-down select-input__icon"></i>
                        <!-- list option -->
                        <ul class="select-input__list">
                            <li class="select-input__item">
                                <a href="#" class="select-input__link">Giá: Thấp đến cao</a>
                            </li>
                            <li class="select-input__item">
                                <a href="#" class="select-input__link">Giá: Cao đến thấp</a>
                            </li>
                        </ul>
                    </div>

                    <div class="home-filter__page">
                        <span class="home-filter__page-num">
                            <span class="home-filter__page-current">1</span>/14
                        </span>

                        <div class="home-filter__page-control">
                            <a href="#" class="home-filter__page-btn  home-filter__page-btn--disable">
                                <i class="fas fa-angle-left home-filter__page-icon"></i>
                            </a>
                            <a href="#" class="home-filter__page-btn">
                                <i class="fas fa-angle-right home-filter__page-icon"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="home-produce">
                    <nav class="mobile__category">
                        <ul class="mobile__category-list">
                            @foreach (var item in ViewBag.ListCategory)
                            {
                                <li class="mobile__category-item">
                                    <a href="#" class="mobile__category-link">@item.Name</a>
                                </li>
                            }
                        </ul>
                    </nav>

                    <!-- List products -->
                    <div class="row-lbr sm-gutter list-product">
                        @foreach (var item in Model)
                        {
                            <div class="col-lbr l-2-4 m-4 c-6-lbr">
                                <a class="home-produce-item" href="/Shop/Detail?id=@item.ID">
                                    <div class="home-produce-item__img"
                                         style="background-image: url('@item.ImagePath');"></div>
                                    <h4 class="home-produce-item__name">
                                        @item.Name
                                    </h4>
                                    <div class="home-produce-item__price">
                                        <span class="home-produce-item__price-old">4600000đ</span>
                                        <span class="home-produce-item__price-new">@item.Price.ToString("#,##")đ</span>
                                    </div>
                                    <div class="home-produce-item__action">
                                        <span class="home-produce-item__like home-produce-item__liked">
                                            <i class="home-produce-item__like-icon--empty far fa-heart"></i>
                                            <i class="home-produce-item__like-icon--fill fas fa-heart"></i>
                                        </span>

                                        <div class="home-produce-item__rating">
                                            <i class="home-produce-item__star-gold fas fa-star"></i>
                                            <i class="home-produce-item__star-gold fas fa-star"></i>
                                            <i class="home-produce-item__star-gold fas fa-star"></i>
                                            <i class="home-produce-item__star-gold fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                        </div>
                                        <span class="home-produce-item__sold">88 đã bán</span>
                                    </div>
                                    <div class="home-produce-item__origin">
                                        <span class="home-produce-item__origin-brand">Whoo</span>
                                        <span class="home-produce-item__origin-name">Nhật bản</span>
                                    </div>
                                    <div class="home-produce-item__favourite">
                                        <i class="fas fa-check"></i>
                                        <span>Yêu thích</span>
                                    </div>
                                    <div class="home-produce-item__sale-off">
                                        <span class="home-produce-item__sale-off-percent">43%</span>
                                        <span class="home-produce-item__sale-off__sale-off-label">Giảm</span>
                                    </div>
                                </a>
                            </div>
                        }


                    </div>
                </div>

                <ul class="pagination produce-pagination">
                    <li class="pagination-item">
                        <a href="#" class="pagination-item__link">
                            <i class="pagination-item__icon fas fa-angle-left"></i>
                        </a>
                    </li>
                    <li class="pagination-item pagination-item-active">
                        <a href="#" class="pagination-item__link">1</a>
                    </li>
                    <li class="pagination-item">
                        <a href="#" class="pagination-item__link">2</a>
                    </li>
                    <li class="pagination-item">
                        <a href="#" class="pagination-item__link">3</a>
                    </li>
                    <li class="pagination-item">
                        <a href="#" class="pagination-item__link">4</a>
                    </li>
                    <li class="pagination-item">
                        <a href="#" class="pagination-item__link">...</a>
                    </li>
                    <li class="pagination-item">
                        <a href="#" class="pagination-item__link">14</a>
                    </li>
                    <li class="pagination-item">
                        <a href="#" class="pagination-item__link">
                            <i class="pagination-item__icon fas fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

</div>